language: r
sudo: true

install:
  - sudo apt-get install latexmk
  - sudo pip install pygments
  - tlmgr install polyglossia minted fvextra ifplatform lstfiracode

script: 
  - latexmk -interaction=nonstopmode main.tex

deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "main.pdf"
  skip_cleanup: true
  on:
    repo: iamm-templates/report-template
