sudo: required
dist: trusty # Ubuntu 14.04
services: docker # Enables docker

script: 
  - ./latex_docker.sh latexmk -cd -f -interaction=batchmode -pdf main.tex
  - mv main.pdf report-template.pdf
deploy:
  provider: releases
  api_key: 
    secure: "${GH_TOKEN}"
  file: "report-template.pdf"
  skip_cleanup: true
  on:
    repo: iamm-templates/report-template
